[build]
  command = "echo 'No build command needed'"
  publish = "."
  functions = "functions"  # Point directly to the functions directory

[build.environment]
  PYTHON_VERSION = "3.9"
  NODE_VERSION = "18"

# API redirects must come before the catch-all redirect
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*", Access-Control-Allow-Headers = "Content-Type", Access-Control-Allow-Methods = "GET, POST, OPTIONS"}

# Catch-all redirect for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

[functions]
  external_node_modules = ["child_process", "path"]
  node_bundler = "esbuild"